# See: Travis Support did recomment moving Android builds to GCE.
# Which is on 'precise' and has larger VMs: https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
sudo: required
dist: precise

notifications:
  irc: "irc.freenode.org#aerogear"

language: android

jdk:
  - oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.3
    - android-24
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-google-google_play_services

env:
  matrix:
    - ANDROID_SDK="android-24" ANDROID_EMULATOR="android-16"  ANDROID_ABI=google_apis/armeabi-v7a   ANDROID_PKGS=addon-google_apis-google-16,sys-img-armeabi-v7a-google_apis-16
    - ANDROID_SDK="android-24" ANDROID_EMULATOR="android-17"  ANDROID_ABI=google_apis/armeabi-v7a   ANDROID_PKGS=addon-google_apis-google-17,sys-img-armeabi-v7a-google_apis-17
    - ANDROID_SDK="android-24" ANDROID_EMULATOR="android-18"  ANDROID_ABI=google_apis/armeabi-v7a   ANDROID_PKGS=addon-google_apis-google-18,sys-img-armeabi-v7a-google_apis-18
    - ANDROID_SDK="android-24" ANDROID_EMULATOR="android-19"  ANDROID_ABI=google_apis/armeabi-v7a   ANDROID_PKGS=addon-google_apis-google-19,sys-img-armeabi-v7a-google_apis-19
    - ANDROID_SDK="android-24" ANDROID_EMULATOR="android-21"  ANDROID_ABI=google_apis/armeabi-v7a   ANDROID_PKGS=addon-google_apis-google-21,sys-img-armeabi-v7a-google_apis-21
    - ANDROID_SDK="android-24" ANDROID_EMULATOR="android-22"  ANDROID_ABI=google_apis/armeabi-v7a   ANDROID_PKGS=addon-google_apis-google-22,sys-img-armeabi-v7a-google_apis-22
    - ANDROID_SDK="android-24" ANDROID_EMULATOR="android-23"  ANDROID_ABI=google_apis/armeabi-v7a   ANDROID_PKGS=addon-google_apis-google-23,sys-img-armeabi-v7a-google_apis-23
    - ANDROID_SDK="android-24" ANDROID_EMULATOR="android-24"  ANDROID_ABI=google_apis/armeabi-v7a   ANDROID_PKGS=addon-google_apis-google-24,sys-img-armeabi-v7a-google_apis-24

before_install:

  #################################################
  ########## maven-android-sdk-deployer ###########
  #################################################

  # Install Android dependencies only on this Matrix
  - echo y | android update sdk --no-ui --all --filter ${ANDROID_EMULATOR},${ANDROID_PKGS}

  # Checkout maven-android-sdk-deployer
  - git clone git://github.com/mosabua/maven-android-sdk-deployer.git

  # Install android maven repository
  - cd $PWD/maven-android-sdk-deployer/platforms/$ANDROID_SDK
  - mvn install -N --quiet
  - cd -

  - cd $PWD/maven-android-sdk-deployer/repositories
  - mvn install --quiet
  - cd -

  #################################################
  ############ Snapshot dependencies ##############
  #################################################

  # AeroGear Android Core
  - git clone git://github.com/aerogear/aerogear-android-core.git
  - cd $PWD/aerogear-android-core
  - mvn install -N --quiet
  - cd -

  # AeroGear Android Pipe
  - git clone git://github.com/aerogear/aerogear-android-pipe.git
  - cd $PWD/aerogear-android-pipe
  - mvn install -DskipTests -fn --quiet
  - cd -

before_script:

  - echo no | android create avd --force -n test -t $ANDROID_EMULATOR --abi $ANDROID_ABI
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
