language: android

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6

android:
  components:
    - build-tools-21.0.2
    - android-21
    - extra-android-support
    - extra-google-google_play_services
    - addon-google_apis-google-21
    - sys-img-armeabi-v7a-android-21

notifications:
  irc: "irc.freenode.org#aerogear"

env:
    matrix:
      - ANDROID_SDKS=android-21 ANDROID_TARGET=android-21 ANDROID_ABI=armeabi-v7a

before_install:

  - echo no | android create avd --force -n test -t 'Google Inc.:Google APIs:21' --abi $ANDROID_ABI 
  - emulator -avd test -no-skin -no-audio -no-window -memory 256&
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

  #################################################
  ########## maven-android-sdk-deployer ###########
  #################################################

  # Checkout maven-android-sdk-deployer
  - git clone git://github.com/mosabua/maven-android-sdk-deployer.git

  # Install android maven repository
  - cd $PWD/maven-android-sdk-deployer/platforms/$ANDROID_TARGET
  - mvn  install -N --quiet
  - cd -

  # Install locally compatibility-v4
  - cd $PWD/maven-android-sdk-deployer/extras/compatibility-v4
  - mvn install -N --quiet
  - cd -

  # Install locally google-play-services
  - cd $PWD/maven-android-sdk-deployer/extras/google-play-services
  - mvn install -N --quiet
  - cd -

  #################################################
  ############ Snapshot dependencies ##############
  #################################################

  # AeroGear Android Core
  - git clone git://github.com/aerogear/aerogear-android-core.git
  - cd $PWD/aerogear-android-core
  - mvn install -N --quiet
  - cd -

  # AeroGear Android Pipe
  - git clone git://github.com/aerogear/aerogear-android-pipe.git
  - cd $PWD/aerogear-android-pipe
  - mvn install -fn --quiet
  - cd -

